services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: app
    container_name: app
    ports:
      - 8000:8000
    env_file:
      - ./docker/app/app.env
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db && \
      python manage.py migrate && \
      python manage.py runserver 0.0.0.0:8000"
    networks:
      - app_network

  db:
    image: postgres
    container_name: app_db
    ports:
      - 5432:5432
    env_file:
      - ./docker/db/db.env
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_volume:

networks:
  app_network:
